// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurchaseOrderApp.Data;

#nullable disable

namespace PurchaseOrderApp.Migrations
{
    [DbContext(typeof(PurchaseOrderContext))]
    [Migration("20260510194029_InvoiceUploaderMetadata")]
    partial class InvoiceUploaderMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("PurchaseOrderApp.Models.AppRole", b =>
                {
                    b.Property<int>("AppRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanAccessConnectivitySettings")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanAccessInventory")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanAccessJobCards")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanAccessPurchaseOrders")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanAccessTrackingCertificates")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanAccessWialonUnits")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanApprovePurchaseOrders")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanManageUsers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanManagerApprovePurchaseOrders")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AppRoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AppRoles");
                });

            modelBuilder.Entity("PurchaseOrderApp.Models.AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordUpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("AppUserId");

                    b.HasIndex("AppRoleId");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("PurchaseOrderApp.Models.InventoryItem", b =>
                {
                    b.Property<int>("InventoryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTrackingUnit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("InventoryItemId");

                    b.HasIndex("ItemCode")
                        .IsUnique();

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("PurchaseOrderApp.Models.InventoryReceipt", b =>
                {
                    b.Property<int>("InventoryReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InventoryReceiptId");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.ToTable("InventoryReceipts");
                });

            modelBuilder.Entity("PurchaseOrderApp.Models.InventoryReceiptLine", b =>
                {
                    b.Property<int>("InventoryReceiptLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategorySnapshot")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryReceiptId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InventoryTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTrackingUnit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemCodeSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemNameSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LineNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PurchaseOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PurchaseOrderNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityReceived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InventoryReceiptLineId");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("InventoryReceiptId");

                    b.HasIndex("InventoryTransactionId");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("ReceiptNumber");

                    b.ToTable("InventoryReceiptLines");
                });

            modelBuilder.Entity("PurchaseOrderApp.Models.InventoryTrackingUnit", b =>
                {
                    b.Property<int>("InventoryTrackingUnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImeiNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIssued")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("IssuedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IssuedInventoryTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssuedJobCardNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IssuedJobCardRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReceivedInventoryTransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InventoryTrackingUnitId");

                    b.HasIndex("ImeiNumber")
                        .IsUnique();

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("IsIssued");

                    b.HasIndex("IssuedInventoryTransactionId");

                    b.HasIndex("ReceivedInventoryTransactionId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("InventoryTrackingUnits");
                });

            modelBuilder.Entity("PurchaseOrderApp.Models.InventoryTransaction", b =>
                {
                    b.Property<int>("InventoryTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategorySnapshot")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTrackingUnit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueOutNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemCodeSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemNameSnapshot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobCardNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JobCardRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityAfterTransaction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InventoryTransactionId");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("IssueOutNumber")
                        .IsUnique();

                    b.HasIndex("JobCardRecordId");

                    b.ToTable("InventoryTransactions");
                });

            modelBuilder.Entity("PurchaseOrderApp.Models.JobCardRecord", b =>
                {
                    b.Property<int>("JobCardRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AmendmentNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("BleSensorQuantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("BleSensorUnitPriceExVat")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomBillingSystemName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DetailsConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EarlyWarningSystemPriceExVat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EvidenceReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasEarlyWarningSystem")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasLvCanAdaptor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPanicButton")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasRegistrationPhoto")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasTrackingUnitPhoto")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasVehiclePhoto")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasVinPhoto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Iccid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobCardName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobCardNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JobCardType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAmendedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LvCanAdaptorPriceExVat")
                        .HasColumnType("TEXT");

                    b.Property<string>("MakeAndModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherHardwareDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherHardwarePriceExVat")
                        .HasColumnType("TEXT");

                    b.Property<string>("PanicButtonPriceExVat")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationFleet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationPlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StatusNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemPriceExVat")
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseCustomBillingSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VehicleClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("WialonAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WialonAccountName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("WialonCreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WialonCreatorName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("WialonHardwareTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WialonHardwareTypeName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("WialonUnitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WialonUnitName")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("JobCardRecordId");

                    b.HasIndex("JobCardNumber")
                        .IsUnique();

                    b.HasIndex("SequenceNumber")
                        .IsUnique();

                    b.ToTable("JobCards");
                });

            modelBuilder.Entity("PurchaseOrderApp.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("PurchaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedManagerAppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedManagerDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BillToAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedByAppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedByDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DirectorApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeVat")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("InvoiceContent")
                        .HasColumnType("BLOB");

                    b.Property<string>("InvoiceFileName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InvoiceUploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InvoiceUploadedByAppUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoiceUploadedByDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ManagerApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OrderNumberManuallyEdited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("SignedOrderContent")
                        .HasColumnType("BLOB");

                    b.Property<string>("SignedOrderFileName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SupplierCopySentAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VATPercent")
                        .HasColumnType("TEXT");

                    b.Property<int>("VendorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PurchaseOrderId");

                    b.HasIndex("VendorId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("PurchaseOrderApp.Models.PurchaseOrderLine", b =>
                {
                    b.Property<int>("PurchaseOrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("PurchaseOrderLineId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderLines");
                });

            modelBuilder.Entity("PurchaseOrderApp.Models.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VendorId");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("PurchaseOrderApp.Models.AppUser", b =>
                {
                    b.HasOne("PurchaseOrderApp.Models.AppRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("AppRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PurchaseOrderApp.Models.InventoryReceiptLine", b =>
                {
                    b.HasOne("PurchaseOrderApp.Models.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseOrderApp.Models.InventoryReceipt", "InventoryReceipt")
                        .WithMany("Lines")
                        .HasForeignKey("InventoryReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseOrderApp.Models.InventoryTransaction", "InventoryTransaction")
                        .WithMany()
                        .HasForeignKey("InventoryTransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("InventoryReceipt");

                    b.Navigation("InventoryTransaction");
                });

            modelBuilder.Entity("PurchaseOrderApp.Models.InventoryTrackingUnit", b =>
                {
                    b.HasOne("PurchaseOrderApp.Models.InventoryItem", "InventoryItem")
                        .WithMany("TrackingUnits")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PurchaseOrderApp.Models.InventoryTransaction", "IssuedInventoryTransaction")
                        .WithMany()
                        .HasForeignKey("IssuedInventoryTransactionId");

                    b.HasOne("PurchaseOrderApp.Models.InventoryTransaction", "ReceivedInventoryTransaction")
                        .WithMany()
                        .HasForeignKey("ReceivedInventoryTransactionId");

                    b.Navigation("InventoryItem");

                    b.Navigation("IssuedInventoryTransaction");

                    b.Navigation("ReceivedInventoryTransaction");
                });

            modelBuilder.Entity("PurchaseOrderApp.Models.InventoryTransaction", b =>
                {
                    b.HasOne("PurchaseOrderApp.Models.InventoryItem", "InventoryItem")
                        .WithMany("Transactions")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("PurchaseOrderApp.Models.PurchaseOrder", b =>
                {
                    b.HasOne("PurchaseOrderApp.Models.Vendor", "Vendor")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("PurchaseOrderApp.Models.PurchaseOrderLine", b =>
                {
                    b.HasOne("PurchaseOrderApp.Models.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("PurchaseOrderApp.Models.AppRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PurchaseOrderApp.Models.InventoryItem", b =>
                {
                    b.Navigation("TrackingUnits");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PurchaseOrderApp.Models.InventoryReceipt", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("PurchaseOrderApp.Models.PurchaseOrder", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("PurchaseOrderApp.Models.Vendor", b =>
                {
                    b.Navigation("PurchaseOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
